server{
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://servidor-bd:5051;
        proxy_set_header Host $host;// Esto es necesario para que el backend pueda saber el host original de la solicitud
        proxy_set_header X-Real-IP $remote_addr;// Esto es necesario para que el backend pueda saber la IP real del cliente
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;// Esto es necesario para el intercambio de información entre el cliente y el servidor
    }

}